# Generated by Django 4.1.11 on 2023-09-07 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import releasemanager.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("package_key", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReleaseState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("release_state_key", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ReleaseGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="release_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "release_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="releasemanager.releasestate",
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(
                        blank=True, null=True, related_name="releases", to="sites.site"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("release_date", models.DateTimeField()),
                (
                    "files",
                    models.JSONField(
                        blank=True,
                        default=releasemanager.models.default_release_paths,
                        help_text="Nested type information for this release",
                        null=True,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="releasemanager.package",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="releasemanager.releasestate",
                    ),
                ),
            ],
            options={
                "ordering": ["-release_date"],
                "unique_together": {("package", "version")},
            },
        ),
    ]
