# Generated by Django 4.1.11 on 2023-09-07 18:29

from django.db import migrations


def create_release_states(apps, schema_editor):
    ReleaseState = apps.get_model("releasemanager", "ReleaseState")

    # Create default ReleaseState records
    release_states = [
        {
            "name": "Production",
            "release_state_key": "production",
            "description": "Production Release",
        },
        {
            "name": "Development",
            "release_state_key": "development",
            "description": "Development Release",
        },
        {"name": "Alpha", "release_state_key": "alpha", "description": "Alpha Release"},
        {"name": "Beta", "release_state_key": "beta", "description": "Beta Release"},
        {
            "name": "Release Candidate",
            "release_state_key": "candidate",
            "description": "Release Candidate",
        },
        {
            "name": "Feature Test",
            "release_state_key": "feature",
            "description": "Feature Test for A/B Testing",
        },
    ]

    for state_data in release_states:
        ReleaseState.objects.create(**state_data)


class Migration(migrations.Migration):
    dependencies = [
        ("releasemanager", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_release_states),
    ]
